import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  ActivityIndicator, Alert
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import AsyncStorage from '@react-native-async-storage/async-storage';

const API_URL = process.env.EXPO_PUBLIC_BACKEND_URL;

export default function QuizScreen() {
  const router = useRouter();
  const [screen, setScreen] = useState<'select' | 'quiz' | 'results'>('select');
  const [loading, setLoading] = useState(false);
  const [tracks, setTracks] = useState<any[]>([]);
  const [selectedTrack, setSelectedTrack] = useState<string>('');
  const [difficulty, setDifficulty] = useState<string>('medium');
  const [quiz, setQuiz] = useState<any>(null);
  const [currentQ, setCurrentQ] = useState(0);
  const [answers, setAnswers] = useState<number[]>([]);
  const [results, setResults] = useState<any>(null);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);

  useEffect(() => { fetchTracks(); }, []);

  const fetchTracks = async () => {
    try {
      const token = await AsyncStorage.getItem('auth_token');
      if (!token) { router.replace('/'); return; }
      const res = await fetch(`${API_URL}/api/tracks`, { headers: { 'Authorization': `Bearer ${token}` } });
      if (res.ok) {
        const data = await res.json();
        setTracks(data);
        if (data.length > 0) setSelectedTrack(data[0].track_id);
      }
    } catch (e) {}
  };

  const startQuiz = async () => {
    if (!selectedTrack) return;
    setLoading(true);
    try {
      const token = await AsyncStorage.getItem('auth_token');
      const res = await fetch(`${API_URL}/api/quiz/generate`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ track_id: selectedTrack, difficulty, num_questions: 5 })
      });
      if (res.ok) {
        const data = await res.json();
        setQuiz(data);
        setCurrentQ(0);
        setAnswers([]);
        setSelectedOption(null);
        setScreen('quiz');
      }
    } catch (e) {}
    setLoading(false);
  };

  const selectAnswer = (optionIdx: number) => {
    setSelectedOption(optionIdx);
  };

  const nextQuestion = () => {
    if (selectedOption === null) return;
    const newAnswers = [...answers, selectedOption];
    setAnswers(newAnswers);
    if (currentQ + 1 < (quiz?.questions?.length || 0)) {
      setCurrentQ(currentQ + 1);
      setSelectedOption(null);
    } else {
      submitQuiz(newAnswers);
    }
  };

  const submitQuiz = async (finalAnswers: number[]) => {
    setLoading(true);
    try {
      const token = await AsyncStorage.getItem('auth_token');
      const res = await fetch(`${API_URL}/api/quiz/submit`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ quiz_id: quiz.quiz_id, answers: finalAnswers })
      });
      if (res.ok) {
        setResults(await res.json());
        setScreen('results');
      }
    } catch (e) {}
    setLoading(false);
  };

  const difficultyColors: Record<string, [string, string]> = {
    easy: ['#00F5D4', '#06B6D4'],
    medium: ['#FF9F1C', '#F59E0B'],
    hard: ['#EF4444', '#F97316'],
  };

  if (screen === 'select') {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity testID="back-from-quiz" onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color="#F8FAFC" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>AI Quiz</Text>
          <View style={{ width: 44 }} />
        </View>
        <ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollContent}>
          <View style={styles.quizIntro}>
            <LinearGradient colors={['#4F46E5', '#7C3AED']} style={styles.quizIcon}>
              <Ionicons name="help-circle" size={40} color="#FFF" />
            </LinearGradient>
            <Text style={styles.quizIntroTitle}>AI-Powered Quiz</Text>
            <Text style={styles.quizIntroDesc}>Test your knowledge with questions generated by AI! Earn XP for correct answers.</Text>
          </View>

          <Text style={styles.selectLabel}>Choose a Track</Text>
          {tracks.map((track: any) => (
            <TouchableOpacity
              key={track.track_id}
              testID={`quiz-track-${track.track_id}`}
              style={[styles.trackOption, selectedTrack === track.track_id && styles.trackOptionSelected]}
              onPress={() => setSelectedTrack(track.track_id)}
            >
              <View style={[styles.radioOuter, selectedTrack === track.track_id && styles.radioOuterSelected]}>
                {selectedTrack === track.track_id && <View style={styles.radioInner} />}
              </View>
              <Text style={[styles.trackOptionText, selectedTrack === track.track_id && styles.trackOptionTextSelected]}>
                {track.title}
              </Text>
            </TouchableOpacity>
          ))}

          <Text style={styles.selectLabel}>Difficulty</Text>
          <View style={styles.diffRow}>
            {['easy', 'medium', 'hard'].map((d) => (
              <TouchableOpacity
                key={d}
                testID={`quiz-diff-${d}`}
                style={[styles.diffBtn, difficulty === d && styles.diffBtnSelected]}
                onPress={() => setDifficulty(d)}
              >
                <Text style={[styles.diffBtnText, difficulty === d && styles.diffBtnTextSelected]}>
                  {d.charAt(0).toUpperCase() + d.slice(1)}
                </Text>
              </TouchableOpacity>
            ))}
          </View>

          <TouchableOpacity testID="start-quiz-btn" onPress={startQuiz} disabled={loading} activeOpacity={0.8}>
            <LinearGradient colors={['#4F46E5', '#7C3AED']} style={styles.startBtn}>
              {loading ? <ActivityIndicator color="#FFF" /> : (
                <>
                  <Ionicons name="play" size={20} color="#FFF" />
                  <Text style={styles.startBtnText}>Start Quiz</Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </ScrollView>
      </View>
    );
  }

  if (screen === 'quiz' && quiz) {
    const question = quiz.questions[currentQ];
    const progress = ((currentQ + 1) / quiz.questions.length) * 100;
    return (
      <View style={styles.container}>
        <View style={styles.quizHeader}>
          <Text style={styles.qProgress}>Question {currentQ + 1} of {quiz.questions.length}</Text>
          <View style={styles.progressBarBg}>
            <LinearGradient colors={['#4F46E5', '#7C3AED']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={[styles.progressBarFill, { width: `${progress}%` }]} />
          </View>
        </View>
        <ScrollView style={styles.scrollView} contentContainerStyle={styles.quizContent}>
          <Text style={styles.questionText}>{question.question}</Text>
          {question.options.map((opt: string, idx: number) => (
            <TouchableOpacity
              key={idx}
              testID={`quiz-option-${idx}`}
              style={[styles.optionBtn, selectedOption === idx && styles.optionSelected]}
              onPress={() => selectAnswer(idx)}
              activeOpacity={0.8}
            >
              <View style={[styles.optionCircle, selectedOption === idx && styles.optionCircleSelected]}>
                <Text style={[styles.optionLetter, selectedOption === idx && styles.optionLetterSelected]}>
                  {String.fromCharCode(65 + idx)}
                </Text>
              </View>
              <Text style={[styles.optionText, selectedOption === idx && styles.optionTextSelected]}>{opt}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
        <View style={styles.footer}>
          <TouchableOpacity testID="next-question-btn" onPress={nextQuestion} disabled={selectedOption === null || loading} activeOpacity={0.8}>
            <LinearGradient
              colors={selectedOption !== null ? ['#4F46E5', '#7C3AED'] : ['#334155', '#334155']}
              style={styles.nextBtn}
            >
              {loading ? <ActivityIndicator color="#FFF" /> : (
                <Text style={styles.nextBtnText}>
                  {currentQ + 1 < quiz.questions.length ? 'Next Question' : 'Submit Quiz'}
                </Text>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  if (screen === 'results' && results) {
    const scoreColor = results.score >= 80 ? '#00F5D4' : results.score >= 50 ? '#FF9F1C' : '#EF4444';
    return (
      <View style={styles.container}>
        <ScrollView style={styles.scrollView} contentContainerStyle={styles.resultsContent}>
          <View style={styles.scoreCircle}>
            <Text style={[styles.scorePercent, { color: scoreColor }]}>{results.score}%</Text>
            <Text style={styles.scoreLabel}>{results.correct}/{results.total} correct</Text>
          </View>
          <Text style={styles.xpEarned}>+{results.xp_earned} XP earned!</Text>
          {results.score >= 80 && <Text style={styles.badgeEarned}>🏆 Quiz Master Badge!</Text>}

          <Text style={styles.reviewTitle}>Review</Text>
          {results.results.map((r: any, i: number) => (
            <View key={i} style={[styles.reviewCard, r.is_correct ? styles.reviewCorrect : styles.reviewWrong]}>
              <View style={styles.reviewHeader}>
                <Ionicons name={r.is_correct ? 'checkmark-circle' : 'close-circle'} size={20} color={r.is_correct ? '#00F5D4' : '#EF4444'} />
                <Text style={styles.reviewQ} numberOfLines={2}>{r.question}</Text>
              </View>
              <Text style={styles.reviewExplanation}>{r.explanation}</Text>
            </View>
          ))}

          <View style={styles.resultsActions}>
            <TouchableOpacity testID="try-again-btn" onPress={() => { setScreen('select'); setQuiz(null); setResults(null); }} activeOpacity={0.8}>
              <LinearGradient colors={['#4F46E5', '#7C3AED']} style={styles.startBtn}>
                <Text style={styles.startBtnText}>Try Another Quiz</Text>
              </LinearGradient>
            </TouchableOpacity>
            <TouchableOpacity testID="back-to-dashboard-btn" style={styles.backToDash} onPress={() => router.push('/dashboard')}>
              <Text style={styles.backToDashText}>Back to Dashboard</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    );
  }

  return <View style={styles.container}><ActivityIndicator size="large" color="#4F46E5" /></View>;
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F172A' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 56, paddingBottom: 16 },
  backBtn: { width: 44, height: 44, justifyContent: 'center' },
  headerTitle: { fontSize: 20, fontWeight: '700', color: '#F8FAFC' },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
  quizIntro: { alignItems: 'center', marginBottom: 32 },
  quizIcon: { width: 80, height: 80, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  quizIntroTitle: { fontSize: 24, fontWeight: '800', color: '#F8FAFC', marginBottom: 8 },
  quizIntroDesc: { fontSize: 15, color: '#94A3B8', textAlign: 'center', lineHeight: 22 },
  selectLabel: { fontSize: 16, fontWeight: '700', color: '#F8FAFC', marginBottom: 12, marginTop: 8 },
  trackOption: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#1E293B', borderRadius: 12, padding: 16, marginBottom: 8, borderWidth: 1, borderColor: '#334155' },
  trackOptionSelected: { borderColor: '#4F46E5', backgroundColor: 'rgba(79,70,229,0.1)' },
  radioOuter: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#475569', justifyContent: 'center', alignItems: 'center' },
  radioOuterSelected: { borderColor: '#4F46E5' },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#4F46E5' },
  trackOptionText: { fontSize: 15, color: '#94A3B8', fontWeight: '600' },
  trackOptionTextSelected: { color: '#F8FAFC' },
  diffRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  diffBtn: { flex: 1, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: '#334155' },
  diffBtnSelected: { borderColor: '#4F46E5', backgroundColor: 'rgba(79,70,229,0.15)' },
  diffBtnText: { fontSize: 14, fontWeight: '600', color: '#64748B' },
  diffBtnTextSelected: { color: '#4F46E5' },
  startBtn: { height: 56, borderRadius: 28, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  startBtnText: { fontSize: 17, fontWeight: '700', color: '#FFF' },
  quizHeader: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 16 },
  qProgress: { fontSize: 14, color: '#94A3B8', marginBottom: 8 },
  progressBarBg: { height: 6, backgroundColor: '#334155', borderRadius: 3, overflow: 'hidden' },
  progressBarFill: { height: 6, borderRadius: 3 },
  quizContent: { paddingHorizontal: 20, paddingBottom: 40 },
  questionText: { fontSize: 20, fontWeight: '700', color: '#F8FAFC', lineHeight: 28, marginBottom: 24, marginTop: 8 },
  optionBtn: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#1E293B', borderRadius: 14, padding: 16, marginBottom: 10, borderWidth: 1.5, borderColor: '#334155' },
  optionSelected: { borderColor: '#4F46E5', backgroundColor: 'rgba(79,70,229,0.1)' },
  optionCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#334155', justifyContent: 'center', alignItems: 'center' },
  optionCircleSelected: { backgroundColor: '#4F46E5' },
  optionLetter: { fontSize: 15, fontWeight: '700', color: '#94A3B8' },
  optionLetterSelected: { color: '#FFF' },
  optionText: { fontSize: 15, color: '#CBD5E1', flex: 1, lineHeight: 22 },
  optionTextSelected: { color: '#F8FAFC', fontWeight: '600' },
  footer: { paddingHorizontal: 20, paddingVertical: 16, borderTopWidth: 1, borderTopColor: '#1E293B', paddingBottom: 32 },
  nextBtn: { height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center' },
  nextBtnText: { fontSize: 17, fontWeight: '700', color: '#FFF' },
  resultsContent: { paddingHorizontal: 20, paddingTop: 80, paddingBottom: 40, alignItems: 'center' },
  scoreCircle: { width: 160, height: 160, borderRadius: 80, backgroundColor: '#1E293B', justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: '#334155', marginBottom: 16 },
  scorePercent: { fontSize: 48, fontWeight: '800' },
  scoreLabel: { fontSize: 14, color: '#94A3B8', marginTop: 4 },
  xpEarned: { fontSize: 20, fontWeight: '700', color: '#FFD700', marginBottom: 8 },
  badgeEarned: { fontSize: 16, color: '#A855F7', marginBottom: 24 },
  reviewTitle: { fontSize: 18, fontWeight: '700', color: '#F8FAFC', alignSelf: 'flex-start', marginTop: 16, marginBottom: 12 },
  reviewCard: { width: '100%', backgroundColor: '#1E293B', borderRadius: 12, padding: 14, marginBottom: 8, borderLeftWidth: 3 },
  reviewCorrect: { borderLeftColor: '#00F5D4' },
  reviewWrong: { borderLeftColor: '#EF4444' },
  reviewHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 6 },
  reviewQ: { fontSize: 14, color: '#F8FAFC', fontWeight: '600', flex: 1 },
  reviewExplanation: { fontSize: 13, color: '#94A3B8', lineHeight: 18, paddingLeft: 28 },
  resultsActions: { width: '100%', marginTop: 24, gap: 12 },
  backToDash: { height: 48, justifyContent: 'center', alignItems: 'center' },
  backToDashText: { fontSize: 15, color: '#4F46E5', fontWeight: '600' },
});
